/* eslint-disable import/no-extraneous-dependencies */
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontSize: {
        '5xs': '8px',
        '4xs': '9px',
        '3xs': '10px',
        '2xs': '11px',
        'tiny': '13px',
        'md': '15px'
      },
      fontFamily: {
        'sans': ['"Poppins"', ...defaultTheme.fontFamily.sans],
        'serif': ['Open Sans', ...defaultTheme.fontFamily.serif],
        'icon': [
          'Material Symbols Outlined',
          {
            fontsize: '24px',
            fontVariationSettings: `"FILL" 0, "wght" 400, "GRAD" 0, "opsz" 24`
          },
        ],
        'icon-filled': [
          'Material Symbols Outlined',
          {
            fontsize: '24px',
            fontVariationSettings: `"FILL" 1, "wght" 400, "GRAD" 0, "opsz" 24`
          },
        ],
      },
      colors: {
        background: 'var(--fac-background)',
        'on-background': 'var(--fac-on-background)',
        inverse: 'var(--fac-inverse)',
        neutral: {
          DEFAULT: 'var(--fac-neutral)',
          0: 'var(--fac-neutral-0)',
          50: 'var(--fac-neutral-50)',
          100: 'var(--fac-neutral-100)',
          200: 'var(--fac-neutral-200)',
          300: 'var(--fac-neutral-300)',
          400: 'var(--fac-neutral-400)',
          450: 'var(--fac-neutral-450)',
          500: 'var(--fac-neutral-500)',
          600: 'var(--fac-neutral-600)',
          650: 'var(--fac-neutral-650)',
          700: 'var(--fac-neutral-700)',
          800: 'var(--fac-neutral-800)',
          900: 'var(--fac-neutral-900)',
          950: 'var(--fac-neutral-950)',
          1000: 'var(--fac-neutral-1000)',
        },
        'neutral-variant': {
          DEFAULT: 'var(--fac-neutral-variant)',
          0: 'var(--fac-neutral-variant-0)',
          50: 'var(--fac-neutral-variant-50)',
          100: 'var(--fac-neutral-variant-100)',
          200: 'var(--fac-neutral-variant-200)',
          300: 'var(--fac-neutral-variant-300)',
          400: 'var(--fac-neutral-variant-400)',
          450: 'var(--fac-neutral-variant-450)',
          500: 'var(--fac-neutral-variant-500)',
          600: 'var(--fac-neutral-variant-600)',
          650: 'var(--fac-neutral-variant-650)',
          700: 'var(--fac-neutral-variant-700)',
          800: 'var(--fac-neutral-variant-800)',
          900: 'var(--fac-neutral-variant-900)',
          950: 'var(--fac-neutral-variant-950)',
          1000: 'var(--fac-neutral-variant-1000)',
        },
        primary: {
          DEFAULT: 'var(--fac-primary)',
          0: 'var(--fac-primary-0)',
          50: 'var(--fac-primary-50)',
          100: 'var(--fac-primary-100)',
          200: 'var(--fac-primary-200)',
          300: 'var(--fac-primary-300)',
          400: 'var(--fac-primary-400)',
          450: 'var(--fac-primary-450)',
          500: 'var(--fac-primary-500)',
          600: 'var(--fac-primary-600)',
          650: 'var(--fac-primary-650)',
          700: 'var(--fac-primary-700)',
          800: 'var(--fac-primary-800)',
          900: 'var(--fac-primary-900)',
          950: 'var(--fac-primary-950)',
          1000: 'var(--fac-primary-1000)',
        },
        secondary: {
          DEFAULT: 'var(--fac-secondary)',
          0: 'var(--fac-secondary-0)',
          50: 'var(--fac-secondary-50)',
          100: 'var(--fac-secondary-100)',
          200: 'var(--fac-secondary-200)',
          300: 'var(--fac-secondary-300)',
          400: 'var(--fac-secondary-400)',
          450: 'var(--fac-secondary-450)',
          500: 'var(--fac-secondary-500)',
          600: 'var(--fac-secondary-600)',
          650: 'var(--fac-secondary-650)',
          700: 'var(--fac-secondary-700)',
          800: 'var(--fac-secondary-800)',
          900: 'var(--fac-secondary-900)',
          950: 'var(--fac-secondary-950)',
          1000: 'var(--fac-secondary-1000)',
        },
        tertiary: {
          DEFAULT: 'var(--fac-tertiary)',
          0: 'var(--fac-tertiary-0)',
          50: 'var(--fac-tertiary-50)',
          100: 'var(--fac-tertiary-100)',
          200: 'var(--fac-tertiary-200)',
          300: 'var(--fac-tertiary-300)',
          400: 'var(--fac-tertiary-400)',
          450: 'var(--fac-tertiary-450)',
          500: 'var(--fac-tertiary-500)',
          600: 'var(--fac-tertiary-600)',
          650: 'var(--fac-tertiary-650)',
          700: 'var(--fac-tertiary-700)',
          800: 'var(--fac-tertiary-800)',
          900: 'var(--fac-tertiary-900)',
          950: 'var(--fac-tertiary-950)',
          1000: 'var(--fac-tertiary-1000)',
        },
        error: {
          DEFAULT: 'var(--fac-error)',
          0: 'var(--fac-error-0)',
          50: 'var(--fac-error-50)',
          100: 'var(--fac-error-100)',
          200: 'var(--fac-error-200)',
          300: 'var(--fac-error-300)',
          400: 'var(--fac-error-400)',
          450: 'var(--fac-error-450)',
          500: 'var(--fac-error-500)',
          600: 'var(--fac-error-600)',
          650: 'var(--fac-error-650)',
          700: 'var(--fac-error-700)',
          800: 'var(--fac-error-800)',
          900: 'var(--fac-error-900)',
          950: 'var(--fac-error-950)',
          1000: 'var(--fac-error-1000)'
        },
        'on-primary': 'var(--fac-on-primary)',
        'primary-container': 'var(--fac-primary-container)',
        'on-primary-container': 'var(--fac-on-primary-container)',
        'primary-fixed': 'var(--fac-primary-fixed)',
        'primary-fixed-dim': 'var(--fac-primary-fixed-dim)',
        'on-primary-fixed': 'var(--fac-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--fac-on-primary-fixed-variant)',

        'on-secondary': 'var(--fac-on-secondary)',
        'secondary-container': 'var(--fac-secondary-container)',
        'on-secondary-container': 'var(--fac-on-secondary-container)',
        'secondary-fixed': 'var(--fac-secondary-fixed)',
        'secondary-fixed-dim': 'var(--fac-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--fac-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--fac-on-secondary-fixed-variant)',

        'on-tertiary': 'var(--fac-on-tertiary)',
        'tertiary-container': 'var(--fac-tertiary-container)',
        'on-tertiary-container': 'var(--fac-on-tertiary-container)',
        'tertiary-fixed': 'var(--fac-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--fac-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--fac-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--fac-on-tertiary-fixed-variant)',

        'on-error': 'var(--fac-on-error)',
        'error-container': 'var(--fac-error-container)',
        'on-error-container': 'var(--fac-on-error-container)',

        'surface': 'var(--fac-surface)',
        'surface-dim': 'var(--fac-surface-dim)',
        'surface-bright': 'var(--fac-surface-bright)',
        'surface-container-lowest': 'var(--fac-surface-container-lowest)',
        'surface-container-low': 'var(--fac-surface-container-low)',
        'surface-container': 'var(--fac-surface-container)',
        'surface-container-high': 'var(--fac-surface-container-high)',
        'surface-container-highest': 'var(--fac-surface-container-highest)',
        'on-surface': 'var(--fac-on-surface)',
        'on-surface-variant': 'var(--fac-on-surface-variant)',

        'outline': 'var(--fac-outline)',
        'outline-variant': 'var(--fac-outline-variant)',

        'inverse-surface': 'var(--fac-inverse-surface)',
        'inverse-on-surface': 'var(--fac-inverse-on-surface)',
        'inverse-primary': 'var(--fac-inverse-primary)',

        'scrim': 'var(--fac-scrim)',
        'shadow': 'var(--fac-shadow)',

        accent: 'var(--fac-accent)',
        warn: 'var(--fac-warn)',
        dark: '#303030'
      }
    }
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries')
  ]
}
